#define S_FUNCTION_NAME cu_irp_perrinn__dy8147eanf3
#ifndef Matlab6
#define Matlab6
#endif
#ifndef Matlab51
#define Matlab51
#endif
#ifndef MatlabR13
#define MatlabR13
#endif
/* Dummy, model has no inputs */
static double u0_[1] = {0.0};

/* Variables for GenerateResultInNonDymosim.c if included */
#if !defined(DYMOLA_DSPACE) && !defined(RT) && !defined(NRT)
#define DYMOLABLOCK_RESULT
char* dymolaBlockResult = "cu_irp_perrinn__dy8147eanf3.mat";
#endif

#if defined(DYM2CCUR) && defined(OMP_DYMOLA)
 #include "ss2dym_rt_omp.c"
#else
 #include "ss2dym.c"
#endif
#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model CU_IRP_perrinn_battery.Test_Bench.Sketch
 Dymola Version 2019 (64-bit), 2018-05-31 translated this at Sun Aug 21 21:53:09 2022

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    4
#define NW_    84
#define NP_    55
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ -715493895
#define NHash2_ 872001811
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  2
#define NSamp_ 0
#define NCons_ 0
#define NA_    103
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="CU_IRP_perrinn_battery.Test_Bench.Sketch";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/jason/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
#if defined(DynSimStruct) || defined(BUILDFMU)
DYNX(W_,0) = 4;
DYNX(W_,12) = 2;
DYNX(W_,17) = 5;
DYNX(W_,49) = 3;
DYNX(W_,60) = 3;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,3) = DYNX(DP_,32);
DYNX(W_,4) = DYNX(DP_,33);
DYNX(W_,5) = DYNX(DP_,34);
DYNX(W_,6) = DYNX(DP_,35);
DYNX(W_,7) = DYNX(DP_,36);
DYNX(W_,8) = DYNX(DP_,37);
DYNX(W_,9) = DYNX(DP_,38);
DYNX(W_,41) = DYNX(DP_,42);
DYNX(W_,11) = DYNX(W_,41);
DYNX(W_,33) = DYNX(DP_,39);
DYNX(W_,30) = DYNX(W_,33);
DYNX(W_,35) = DYNX(DP_,1);
DYNX(W_,31) = DYNX(W_,35);
DYNX(W_,34) = DYNX(DP_,40);
DYNX(W_,36) = DYNX(DP_,41);
DYNX(W_,38) = DYNX(W_,34);
DYNX(W_,39) = DYNX(W_,36);
DYNX(W_,44) = DYNX(W_,7);
DYNX(W_,52) = DYNX(W_,9);
DYNX(W_,63) = DYNX(DP_,49);
DYNX(W_,53) = DYNX(W_,63);
DYNX(W_,65) = DYNX(DP_,47);
DYNX(W_,54) = DYNX(W_,65);
DYNX(W_,55) = DYNX(W_,41);
DYNX(W_,64) = DYNX(DP_,50);
DYNX(W_,66) = DYNX(DP_,48);
DYNX(W_,72) = DYNX(DP_,51);
DYNX(W_,67) = DYNX(W_,72);
DYNX(W_,74) = DYNX(DP_,53);
DYNX(W_,68) = DYNX(W_,74);
DYNX(W_,73) = DYNX(DP_,52);
DYNX(W_,70) = DYNX(W_,73);
DYNX(W_,75) = DYNX(DP_,54);
DYNX(W_,71) = DYNX(W_,75);
DYNX(W_,76) = DYNX(W_,9);
DYNX(W_,77) = DYNX(W_,63);
DYNX(W_,78) = DYNX(W_,65);
DYNX(W_,79) = DYNX(W_,41);
BoundParameterConstantSection
DYNX(W_,47) = divmacro(DYNX(W_,8)*DYNX(DP_,0),"ro.Rbar*Temp.k",DYNX(W_,9),"ro.F");
DYNX(W_,40) = DYNX(DP_,29)*DYNX(W_,38);
DYNX(W_,37) = divmacro(DYNX(W_,40),"ro.a_a.gain.y",DYNX(W_,39),"ro.a_a.R");
DYNX(W_,61) = DYNX(W_,7)*DYNX(W_,5);
DYNX(W_,80) = DYNX(W_,76)*DYNX(W_,77);
DYNX(W_,45) = divmacro(DYNX(W_,8)*DYNX(DP_,0),"ro.Rbar*Temp.k",DYNX(W_,9),"ro.F");
DYNX(W_,32) = DYNX(DP_,28)*DYNX(W_,30);
DYNX(W_,29) = divmacro(DYNX(W_,32),"ro.a_c.gain.y",DYNX(W_,31),"ro.a_c.R");
DYNX(W_,50) = DYNX(W_,7)*DYNX(W_,3);
DYNX(W_,56) = DYNX(W_,52)*DYNX(W_,53);
DYNX(Y_,0) = DYNX(DP_,35);
DYNX(W_,42) = DYNX(W_,3)+DYNX(W_,4)+DYNX(W_,5);
DYNX(W_,18) = DYNX(DP_,15)*DYNX(DP_,0);
DYNX(W_,13) = DYNX(DP_,0)*DYNX(DP_,0);
DYNX(W_,19) = DYNX(DP_,16)*DYNX(W_,13);
DYNX(W_,23) = DYNX(DP_,17)*DYNX(DP_,0);
DYNX(W_,24) = DYNX(DP_,18)*DYNX(W_,13);
DYNX(W_,20) = DYNX(DP_,22)*DYNX(DP_,21)+DYNX(DP_,23)*DYNX(W_,23)+DYNX(DP_,24)*
  DYNX(W_,24);
DYNX(W_,25) = DYNX(DP_,19)*DYNX(DP_,0);
DYNX(W_,27) = DYNX(DP_,25)*DYNX(DP_,20)+DYNX(DP_,26)*DYNX(W_,25);
DYNX(W_,26) = DYNX(W_,11)*0.001;
DYNX(W_,28) = DYNX(W_,26)*DYNX(W_,26);
DYNX(W_,21) = DYNX(W_,27)*DYNX(W_,28);
DYNX(W_,22) = DYNX(DP_,10)*DYNX(DP_,8)+DYNX(DP_,11)*DYNX(W_,18)+DYNX(DP_,12)*
  DYNX(W_,19)+DYNX(DP_,13)*DYNX(W_,20)+DYNX(DP_,14)*DYNX(W_,21);
DYNX(W_,14) = DYNX(W_,22)*DYNX(W_,22);
DYNX(W_,15) = DYNX(W_,11)*0.001;
DYNX(W_,16) = DYNX(W_,14)*DYNX(W_,15);
DYNX(W_,10) = DYNX(DP_,27)*DYNX(W_,16);
DYNX(W_,43) = DYNX(W_,44)*DYNX(W_,10);
DYNX(W_,83) = divmacro(DYNX(W_,42),"ro.division.u1",DYNX(W_,43),"ro.division.u2");
DYNX(Y_,1) = DYNX(W_,83);
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(W_,2) = DYNX(DP_,45)+(IF LessTime(DYNX(DP_,46), 0) THEN 0 ELSE IF LessTime(
  DYNX(DP_,46)+DYNX(DP_,44), 1) THEN divmacro((DYNTime-DYNX(DP_,46))*
  DYNX(DP_,43),"(time-SoC.startTime)*SoC.height",DYNX(DP_,44),"SoC.duration")
   ELSE DYNX(DP_,43));
DYNX(W_,69) = DYNX(W_,70)+DYNX(W_,2)*(DYNX(W_,71)-DYNX(W_,70));
DYNX(W_,81) = DYNX(W_,69)*DYNX(W_,78)*DYNX(W_,79)*(DYNX(W_,78)-DYNX(W_,69)*
  DYNX(W_,78));
DYNX(W_,82) = sqrtGuarded(DYNX(W_,81),"ro.i0_a_ref.F_express1.y");
DYNX(W_,62) = DYNX(W_,80)*DYNX(W_,82);
DYNX(W_,48) = DYNX(W_,37)*DYNX(W_,61)*DYNX(W_,62);
DYNX(Y_,2) = divmacro(DYNX(W_,47),"ro.division2.u1",DYNX(W_,48),"ro.division2.u2");
DYNX(W_,59) = DYNX(W_,67)+DYNX(W_,2)*(DYNX(W_,68)-DYNX(W_,67));
DYNX(W_,57) = DYNX(W_,59)*DYNX(W_,54)*DYNX(W_,55)*(DYNX(W_,54)-DYNX(W_,59)*
  DYNX(W_,54));
DYNX(W_,58) = sqrtGuarded(DYNX(W_,57),"ro.i0_c_ref.F_express1.y");
DYNX(W_,51) = DYNX(W_,56)*DYNX(W_,58);
DYNX(W_,46) = DYNX(W_,29)*DYNX(W_,50)*DYNX(W_,51);
DYNX(Y_,3) = divmacro(DYNX(W_,45),"ro.ConstantFor3and4Term1.y",DYNX(W_,46),
  "ro.division1.u2");

DynamicsSection

AcceptedSection1

AcceptedSection2
DYNX(W_,1) = DYNX(DP_,3)*DYNX(W_,6)+DYNX(DP_,4)*DYNX(W_,83)+DYNX(DP_,5)*
  DYNX(Y_,3)+DYNX(DP_,6)*DYNX(Y_,2);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("Temp.k", "Constant output value", 0, 298.15, 0.0,0.0,0.0,0,560)
DeclareAlias2("Temp.y", "Connector of Real output signal", "Temp.k", 1, 7, 0, 0)
DeclareParameter("radius_c.k", "Constant output value", 1, 4E-06, 0.0,0.0,0.0,0,560)
DeclareAlias2("radius_c.y", "Connector of Real output signal", "radius_c.k", 1, 7,\
 1, 0)
DeclareParameter("ro.multiSum.significantDigits", "Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 2, 3, 1.0,1E+100,0.0,0,564)
DeclareVariable("ro.multiSum.nu", "Number of input connections [:#(type=Integer)]",\
 4, 0.0,1E+100,0.0,0,1541)
DeclareAlias2("ro.multiSum.u[1]", "", "ro.Rcc", 1, 5, 6, 0)
DeclareAlias2("ro.multiSum.u[2]", "", "phi_ohmic_express.y", 1, 5, 83, 0)
DeclareAlias2("ro.multiSum.u[3]", "", "eta_c", 1, 3, 3, 0)
DeclareAlias2("ro.multiSum.u[4]", "", "eta_a", 1, 3, 2, 0)
DeclareAlias2("ro.multiSum.y", "", "ro.y", 1, 5, 1, 0)
DeclareParameter("ro.multiSum.k[1]", "Input gains", 3, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("ro.multiSum.k[2]", "Input gains", 4, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("ro.multiSum.k[3]", "Input gains", 5, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("ro.multiSum.k[4]", "Input gains", 6, 1, 0.0,0.0,0.0,0,560)
DeclareVariable("ro.y", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("ro.SoC", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("ro.Temp", "Temperature in Kelvins", "Temp.k", 1, 7, 0, 0)
DeclareVariable("ro.Lc", "Thickness of cathode", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.Ls", "Thickness of seperator", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.La", "Thickness of anode", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.Rcc", "Current Collector Resistance in Ohms", 0.0, 0.0,0.0,\
0.0,0,513)
DeclareVariable("ro.A", "Electrode area in square meter [1]", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.Rbar", "Universal Gas constant, 8.314 J/mol K", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.F", "Faraday's Constant, Coulmb/mol, Ampere-second/mol", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("ro.sigma_e1.y", "effective ionic conductivity of electrolyte, mS/cm",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("ro.sigma_e1.Temp", "Temperature in Kelvins", "Temp.k", 1, 7, 0, 0)
DeclareVariable("ro.sigma_e1.Ce_0", "Initial Electrolyte Concentration in mol/m^3, 1e3",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("ro.sigma_e1.T_square.significantDigits", "Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 7, 3, 1.0,1E+100,0.0,0,564)
DeclareVariable("ro.sigma_e1.T_square.nu", "Number of input connections [:#(type=Integer)]",\
 2, 0.0,1E+100,0.0,0,1541)
DeclareAlias2("ro.sigma_e1.T_square.u[1]", "", "Temp.k", 1, 7, 0, 0)
DeclareAlias2("ro.sigma_e1.T_square.u[2]", "", "Temp.k", 1, 7, 0, 0)
DeclareVariable("ro.sigma_e1.T_square.y", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("ro.sigma_e1.K00.k", "Constant output value", 8, -10.5, \
0.0,0.0,0.0,0,560)
DeclareAlias2("ro.sigma_e1.K00.y", "Connector of Real output signal", \
"ro.sigma_e1.K00.k", 1, 7, 8, 0)
DeclareVariable("ro.sigma_e1.product.u1", "Connector of Real input signal 1", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.sigma_e1.product.u2", "Connector of Real input signal 2", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.sigma_e1.product.y", "Connector of Real output signal", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareParameter("ro.sigma_e1.multiSum.significantDigits", "Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 9, 3, 1.0,1E+100,0.0,0,564)
DeclareVariable("ro.sigma_e1.multiSum.nu", "Number of input connections [:#(type=Integer)]",\
 5, 0.0,1E+100,0.0,0,1541)
DeclareAlias2("ro.sigma_e1.multiSum.u[1]", "", "ro.sigma_e1.K00.k", 1, 7, 8, 0)
DeclareVariable("ro.sigma_e1.multiSum.u[2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.sigma_e1.multiSum.u[3]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.sigma_e1.multiSum.u[4]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.sigma_e1.multiSum.u[5]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.sigma_e1.multiSum.y", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("ro.sigma_e1.multiSum.k[1]", "Input gains", 10, 1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("ro.sigma_e1.multiSum.k[2]", "Input gains", 11, 1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("ro.sigma_e1.multiSum.k[3]", "Input gains", 12, 1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("ro.sigma_e1.multiSum.k[4]", "Input gains", 13, 1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("ro.sigma_e1.multiSum.k[5]", "Input gains", 14, 1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("ro.sigma_e1.K01.k", "Gain value multiplied with input signal [1]",\
 15, 0.074, 0.0,0.0,0.0,0,560)
DeclareAlias2("ro.sigma_e1.K01.u", "Input signal connector", "Temp.k", 1, 7, 0, 0)
DeclareAlias2("ro.sigma_e1.K01.y", "Output signal connector", "ro.sigma_e1.multiSum.u[2]", 1,\
 5, 18, 0)
DeclareParameter("ro.sigma_e1.K02.k", "Gain value multiplied with input signal [1]",\
 16, -6.96E-05, 0.0,0.0,0.0,0,560)
DeclareAlias2("ro.sigma_e1.K02.u", "Input signal connector", "ro.sigma_e1.T_square.y", 1,\
 5, 13, 0)
DeclareAlias2("ro.sigma_e1.K02.y", "Output signal connector", "ro.sigma_e1.multiSum.u[3]", 1,\
 5, 19, 0)
DeclareParameter("ro.sigma_e1.K11.k", "Gain value multiplied with input signal [1]",\
 17, -0.0178, 0.0,0.0,0.0,0,560)
DeclareAlias2("ro.sigma_e1.K11.u", "Input signal connector", "Temp.k", 1, 7, 0, 0)
DeclareVariable("ro.sigma_e1.K11.y", "Output signal connector", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareParameter("ro.sigma_e1.K12.k", "Gain value multiplied with input signal [1]",\
 18, 2.8E-05, 0.0,0.0,0.0,0,560)
DeclareAlias2("ro.sigma_e1.K12.u", "Input signal connector", "ro.sigma_e1.T_square.y", 1,\
 5, 13, 0)
DeclareVariable("ro.sigma_e1.K12.y", "Output signal connector", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareParameter("ro.sigma_e1.K21.k", "Gain value multiplied with input signal [1]",\
 19, -0.000886, 0.0,0.0,0.0,0,560)
DeclareAlias2("ro.sigma_e1.K21.u", "Input signal connector", "Temp.k", 1, 7, 0, 0)
DeclareVariable("ro.sigma_e1.K21.y", "Output signal connector", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareVariable("ro.sigma_e1.realExpression2.y", "Value of Real output", 0.0, \
0.0,0.0,0.0,0,513)
DeclareParameter("ro.sigma_e1.K20.k", "Constant output value", 20, 0.494, \
0.0,0.0,0.0,0,560)
DeclareAlias2("ro.sigma_e1.K20.y", "Connector of Real output signal", \
"ro.sigma_e1.K20.k", 1, 7, 20, 0)
DeclareParameter("ro.sigma_e1.K10.k", "Constant output value", 21, 0.668, \
0.0,0.0,0.0,0,560)
DeclareAlias2("ro.sigma_e1.K10.y", "Connector of Real output signal", \
"ro.sigma_e1.K10.k", 1, 7, 21, 0)
DeclareParameter("ro.sigma_e1.add3_1.k1", "Gain of upper input", 22, 1, 0.0,0.0,\
0.0,0,560)
DeclareParameter("ro.sigma_e1.add3_1.k2", "Gain of middle input", 23, 1, \
0.0,0.0,0.0,0,560)
DeclareParameter("ro.sigma_e1.add3_1.k3", "Gain of lower input", 24, 1, 0.0,0.0,\
0.0,0,560)
DeclareAlias2("ro.sigma_e1.add3_1.u1", "Connector 1 of Real input signals", \
"ro.sigma_e1.K10.k", 1, 7, 21, 0)
DeclareAlias2("ro.sigma_e1.add3_1.u2", "Connector 2 of Real input signals", \
"ro.sigma_e1.K11.y", 1, 5, 23, 0)
DeclareAlias2("ro.sigma_e1.add3_1.u3", "Connector 3 of Real input signals", \
"ro.sigma_e1.K12.y", 1, 5, 24, 0)
DeclareAlias2("ro.sigma_e1.add3_1.y", "Connector of Real output signals", \
"ro.sigma_e1.multiSum.u[4]", 1, 5, 20, 0)
DeclareVariable("ro.sigma_e1.product1.u1", "Connector of Real input signal 1", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.sigma_e1.product1.u2", "Connector of Real input signal 2", \
0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("ro.sigma_e1.product1.y", "Connector of Real output signal", \
"ro.sigma_e1.multiSum.u[5]", 1, 5, 21, 0)
DeclareAlias2("ro.sigma_e1.product2.u1", "Connector of Real input signal 1", \
"ro.sigma_e1.multiSum.y", 1, 5, 22, 0)
DeclareAlias2("ro.sigma_e1.product2.u2", "Connector of Real input signal 2", \
"ro.sigma_e1.multiSum.y", 1, 5, 22, 0)
DeclareAlias2("ro.sigma_e1.product2.y", "Connector of Real output signal", \
"ro.sigma_e1.product.u1", 1, 5, 14, 0)
DeclareAlias2("ro.sigma_e1.product3.u1", "Connector of Real input signal 1", \
"ro.sigma_e1.realExpression2.y", 1, 5, 26, 0)
DeclareAlias2("ro.sigma_e1.product3.u2", "Connector of Real input signal 2", \
"ro.sigma_e1.realExpression2.y", 1, 5, 26, 0)
DeclareAlias2("ro.sigma_e1.product3.y", "Connector of Real output signal", \
"ro.sigma_e1.product1.u2", 1, 5, 28, 0)
DeclareAlias2("ro.sigma_e1.add.u1", "Connector of Real input signal 1", \
"ro.sigma_e1.K20.k", 1, 7, 20, 0)
DeclareAlias2("ro.sigma_e1.add.u2", "Connector of Real input signal 2", \
"ro.sigma_e1.K21.y", 1, 5, 25, 0)
DeclareAlias2("ro.sigma_e1.add.y", "Connector of Real output signal", \
"ro.sigma_e1.product1.u1", 1, 5, 27, 0)
DeclareParameter("ro.sigma_e1.add.k1", "Gain of upper input", 25, 1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("ro.sigma_e1.add.k2", "Gain of lower input", 26, 1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("ro.sigma_e1.Gain.k", "Gain value multiplied with input signal [1]",\
 27, 0.1, 0.0,0.0,0.0,0,560)
DeclareAlias2("ro.sigma_e1.Gain.u", "Input signal connector", "ro.sigma_e1.product.y", 1,\
 5, 16, 0)
DeclareAlias2("ro.sigma_e1.Gain.y", "Output signal connector", "ro.sigma_e1.y", 1,\
 5, 10, 0)
DeclareAlias2("ro.sigma_e1.realExpression1.y", "Value of Real output", \
"ro.sigma_e1.product.u2", 1, 5, 15, 0)
DeclareVariable("ro.a_c.y", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.a_c.epsilon", "active material volume fraction", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.a_c.R", "particle size in m, magnitude is usually 1e-6", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareParameter("ro.a_c.gain.k", "Gain value multiplied with input signal [1]",\
 28, 3, 0.0,0.0,0.0,0,560)
DeclareAlias2("ro.a_c.gain.u", "Input signal connector", "ro.a_c.epsilon", 1, 5,\
 30, 0)
DeclareVariable("ro.a_c.gain.y", "Output signal connector", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("ro.a_c.division.u1", "Connector of Real input signal 1", \
"ro.a_c.gain.y", 1, 5, 32, 0)
DeclareAlias2("ro.a_c.division.u2", "Connector of Real input signal 2", \
"ro.a_c.R", 1, 5, 31, 0)
DeclareAlias2("ro.a_c.division.y", "Connector of Real output signal", "ro.a_c.y", 1,\
 5, 29, 0)
DeclareVariable("ro.epsilon_c", "active material volume fraction of cathode", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.epsilon_a", "active material volume fraction of anode", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareVariable("ro.radius_c", "particle radius of cathode active material, in m, magnitude usually 1e-6",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.radius_a", "particle radius of anode active material, in m, magnitude usually 1e-6",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.a_a.y", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.a_a.epsilon", "active material volume fraction", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.a_a.R", "particle size in m, magnitude is usually 1e-6", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareParameter("ro.a_a.gain.k", "Gain value multiplied with input signal [1]",\
 29, 3, 0.0,0.0,0.0,0,560)
DeclareAlias2("ro.a_a.gain.u", "Input signal connector", "ro.a_a.epsilon", 1, 5,\
 38, 0)
DeclareVariable("ro.a_a.gain.y", "Output signal connector", 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("ro.a_a.division.u1", "Connector of Real input signal 1", \
"ro.a_a.gain.y", 1, 5, 40, 0)
DeclareAlias2("ro.a_a.division.u2", "Connector of Real input signal 2", \
"ro.a_a.R", 1, 5, 39, 0)
DeclareAlias2("ro.a_a.division.y", "Connector of Real output signal", "ro.a_a.y", 1,\
 5, 37, 0)
DeclareVariable("ro.Ce_0", "Initial Electrolyte concentration, in mol/m^3, usually 1e3",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("ro.Temp_express.y", "Value of Real output", "Temp.k", 1, 7, 0, 0)
DeclareVariable("ro.division.u1", "Connector of Real input signal 1", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.division.u2", "Connector of Real input signal 2", 0.0, \
0.0,0.0,0.0,0,513)
DeclareAlias2("ro.division.y", "Connector of Real output signal", \
"phi_ohmic_express.y", 1, 5, 83, 0)
DeclareAlias2("ro.Rcc_express.y", "Value of Real output", "ro.Rcc", 1, 5, 6, 0)
DeclareVariable("ro.gain.k", "Gain value multiplied with input signal [1]", 1, \
0.0,0.0,0.0,0,513)
DeclareAlias2("ro.gain.u", "Input signal connector", "ro.sigma_e1.y", 1, 5, 10, 0)
DeclareAlias2("ro.gain.y", "Output signal connector", "ro.division.u2", 1, 5, 43,\
 0)
DeclareAlias2("ro.Lt.y", "Value of Real output", "ro.division.u1", 1, 5, 42, 0)
DeclareVariable("ro.ConstantFor3and4Term1.y", "Value of Real output", 0.0, \
0.0,0.0,0.0,0,513)
DeclareAlias2("ro.division1.u1", "Connector of Real input signal 1", \
"ro.ConstantFor3and4Term1.y", 1, 5, 45, 0)
DeclareVariable("ro.division1.u2", "Connector of Real input signal 2", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("ro.division1.y", "Connector of Real output signal", "eta_c", 1, 3,\
 3, 0)
DeclareVariable("ro.division2.u1", "Connector of Real input signal 1", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.division2.u2", "Connector of Real input signal 2", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("ro.division2.y", "Connector of Real output signal", "eta_a", 1, 3,\
 2, 0)
DeclareAlias2("ro.ConstantFor3and4Term.y", "Value of Real output", \
"ro.division2.u1", 1, 5, 47, 0)
DeclareParameter("ro.multiProduct.significantDigits", "Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 30, 3, 1.0,1E+100,0.0,0,564)
DeclareVariable("ro.multiProduct.nu", "Number of input connections [:#(type=Integer)]",\
 3, 0.0,1E+100,0.0,0,1541)
DeclareAlias2("ro.multiProduct.u[1]", "", "ro.a_c.y", 1, 5, 29, 0)
DeclareVariable("ro.multiProduct.u[2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.multiProduct.u[3]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("ro.multiProduct.y", "", "ro.division1.u2", 1, 5, 46, 0)
DeclareAlias2("ro.A_express.y", "Value of Real output", "ro.multiProduct.u[2]", 1,\
 5, 50, 0)
DeclareAlias2("ro.i0_c_ref.y", "", "ro.multiProduct.u[3]", 1, 5, 51, 0)
DeclareVariable("ro.i0_c_ref.F", "Faraday's Constant, Coulmb/mol, Ampere-second/mol",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_c_ref.k", "electrode reaction rate coefficient, kinetic rate constants",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_c_ref.c_max", "Maximum concentration at the electrode, mol/m^3",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_c_ref.Ce_0", "Initial Electrolyte Concentration in mol/m^3, 1e3",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_c_ref.Fk_express.y", "Value of Real output", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_c_ref.F_express1.y", "Value of Real output", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("ro.i0_c_ref.sqrt1.u", "Connector of Real input signal", \
"ro.i0_c_ref.F_express1.y", 1, 5, 57, 0)
DeclareVariable("ro.i0_c_ref.sqrt1.y", "Connector of Real output signal", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("ro.i0_c_ref.product.u1", "Connector of Real input signal 1", \
"ro.i0_c_ref.Fk_express.y", 1, 5, 56, 0)
DeclareAlias2("ro.i0_c_ref.product.u2", "Connector of Real input signal 2", \
"ro.i0_c_ref.sqrt1.y", 1, 5, 58, 0)
DeclareAlias2("ro.i0_c_ref.product.y", "Connector of Real output signal", \
"ro.multiProduct.u[3]", 1, 5, 51, 0)
DeclareVariable("ro.i0_c_ref.theta", "Molar Fraction at the electrode", 0.0, \
0.0,0.0,0.0,0,512)
DeclareParameter("ro.multiProduct1.significantDigits", "Number of significant digits to be shown in dynamic diagram layer for y [:#(type=Integer)]",\
 31, 3, 1.0,1E+100,0.0,0,564)
DeclareVariable("ro.multiProduct1.nu", "Number of input connections [:#(type=Integer)]",\
 3, 0.0,1E+100,0.0,0,1541)
DeclareAlias2("ro.multiProduct1.u[1]", "", "ro.a_a.y", 1, 5, 37, 0)
DeclareVariable("ro.multiProduct1.u[2]", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.multiProduct1.u[3]", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("ro.multiProduct1.y", "", "ro.division2.u2", 1, 5, 48, 0)
DeclareAlias2("ro.A_express1.y", "Value of Real output", "ro.multiProduct1.u[2]", 1,\
 5, 61, 0)
DeclareVariable("ro.kc", "kinetic rate constant for cathode, reaction rate coefficient",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.ka", "kinetic rate constant for anode, reaction rate coefficient",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.c_max_c", "Maximum concentration of cathode, in mol/m^3", \
0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.c_max_a", "Maximum concentration of anode, in mol/m^3", 0.0,\
 0.0,0.0,0.0,0,513)
DeclareAlias2("ro.soC_theta_c.y", "", "ro.i0_c_ref.theta", 1, 5, 59, 0)
DeclareAlias2("ro.soC_theta_c.F_express.y", "Value of Real output", \
"ro.i0_c_ref.theta", 1, 5, 59, 0)
DeclareAlias2("ro.soC_theta_c.SoC", "", "ro.SoC", 1, 5, 2, 0)
DeclareVariable("ro.soC_theta_c.theta_0", "Molar Fraction of electrode at 0% SoC",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.soC_theta_c.theta_100", "Molar Fraction of electrode at 100% SoC",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("ro.SoC_express.y", "Value of Real output", "ro.SoC", 1, 5, 2, 0)
DeclareVariable("ro.soC_theta_a.y", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("ro.soC_theta_a.F_express.y", "Value of Real output", \
"ro.soC_theta_a.y", 1, 5, 69, 0)
DeclareAlias2("ro.soC_theta_a.SoC", "", "ro.SoC", 1, 5, 2, 0)
DeclareVariable("ro.soC_theta_a.theta_0", "Molar Fraction of electrode at 0% SoC",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.soC_theta_a.theta_100", "Molar Fraction of electrode at 100% SoC",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.theta_0_c", "Molar Fraction of cathode at 0% SoC", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.theta_0_a", "Molar Fraction of anode at 0% SoC", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.theta_100_c", "Molar Fraction of cathode at 100% SoC", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.theta_100_a", "Molar Fraction of anode at 1 SoC", 0.0, \
0.0,0.0,0.0,0,513)
DeclareAlias2("ro.i0_a_ref.y", "", "ro.multiProduct1.u[3]", 1, 5, 62, 0)
DeclareVariable("ro.i0_a_ref.F", "Faraday's Constant, Coulmb/mol, Ampere-second/mol",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_a_ref.k", "electrode reaction rate coefficient, kinetic rate constants",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_a_ref.c_max", "Maximum concentration at the electrode, mol/m^3",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_a_ref.Ce_0", "Initial Electrolyte Concentration in mol/m^3, 1e3",\
 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_a_ref.Fk_express.y", "Value of Real output", 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("ro.i0_a_ref.F_express1.y", "Value of Real output", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("ro.i0_a_ref.sqrt1.u", "Connector of Real input signal", \
"ro.i0_a_ref.F_express1.y", 1, 5, 81, 0)
DeclareVariable("ro.i0_a_ref.sqrt1.y", "Connector of Real output signal", 0.0, \
0.0,0.0,0.0,0,512)
DeclareAlias2("ro.i0_a_ref.product.u1", "Connector of Real input signal 1", \
"ro.i0_a_ref.Fk_express.y", 1, 5, 80, 0)
DeclareAlias2("ro.i0_a_ref.product.u2", "Connector of Real input signal 2", \
"ro.i0_a_ref.sqrt1.y", 1, 5, 82, 0)
DeclareAlias2("ro.i0_a_ref.product.y", "Connector of Real output signal", \
"ro.multiProduct1.u[3]", 1, 5, 62, 0)
DeclareAlias2("ro.i0_a_ref.theta", "Molar Fraction at the electrode", \
"ro.soC_theta_a.y", 1, 5, 69, 0)
DeclareParameter("Lc.k", "Constant output value", 32, 7.5E-05, 0.0,0.0,0.0,0,560)
DeclareAlias2("Lc.y", "Connector of Real output signal", "Lc.k", 1, 7, 32, 0)
DeclareParameter("Ls.k", "Constant output value", 33, 2E-05, 0.0,0.0,0.0,0,560)
DeclareAlias2("Ls.y", "Connector of Real output signal", "Ls.k", 1, 7, 33, 0)
DeclareParameter("La.k", "Constant output value", 34, 7E-05, 0.0,0.0,0.0,0,560)
DeclareAlias2("La.y", "Connector of Real output signal", "La.k", 1, 7, 34, 0)
DeclareParameter("Rcc.k", "Constant output value", 35, 0.0004, 0.0,0.0,0.0,0,560)
DeclareAlias2("Rcc.y", "Connector of Real output signal", "Rcc.k", 1, 7, 35, 0)
DeclareParameter("A.k", "Constant output value [1]", 36, 2, 0.0,0.0,0.0,0,560)
DeclareAlias2("A.y", "Connector of Real output signal [1]", "A.k", 1, 7, 36, 0)
DeclareParameter("Rbar.k", "Constant output value", 37, 8.314, 0.0,0.0,0.0,0,560)
DeclareAlias2("Rbar.y", "Connector of Real output signal", "Rbar.k", 1, 7, 37, 0)
DeclareParameter("F.k", "Constant output value", 38, 96500.0, 0.0,0.0,0.0,0,560)
DeclareAlias2("F.y", "Connector of Real output signal", "F.k", 1, 7, 38, 0)
DeclareParameter("epsilon_c.k", "Constant output value", 39, 0.546, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("epsilon_c.y", "Connector of Real output signal", "epsilon_c.k", 1,\
 7, 39, 0)
DeclareParameter("epsilon_a.k", "Constant output value", 40, 0.51, 0.0,0.0,0.0,0,560)
DeclareAlias2("epsilon_a.y", "Connector of Real output signal", "epsilon_a.k", 1,\
 7, 40, 0)
DeclareParameter("radius_a.k", "Constant output value", 41, 3E-06, 0.0,0.0,0.0,0,560)
DeclareAlias2("radius_a.y", "Connector of Real output signal", "radius_a.k", 1, 7,\
 41, 0)
DeclareParameter("Ce_0.k", "Constant output value", 42, 1000.0, 0.0,0.0,0.0,0,560)
DeclareAlias2("Ce_0.y", "Connector of Real output signal", "Ce_0.k", 1, 7, 42, 0)
DeclareParameter("SoC.height", "Height of ramps", 43, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("SoC.duration", "Duration of ramp (= 0.0 gives a Step) [s]", 44,\
 1, 0.0,1E+100,0.0,0,560)
DeclareParameter("SoC.offset", "Offset of output signal", 45, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("SoC.startTime", "Output = offset for time < startTime [s]", 46,\
 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("SoC.y", "Connector of Real output signal", "ro.SoC", 1, 5, 2, 0)
DeclareParameter("c_max_c.k", "Constant output value", 47, 43000.0, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("c_max_c.y", "Connector of Real output signal", "c_max_c.k", 1, 7,\
 47, 0)
DeclareParameter("c_max_a.k", "Constant output value", 48, 31300.0, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("c_max_a.y", "Connector of Real output signal", "c_max_a.k", 1, 7,\
 48, 0)
DeclareParameter("kc.k", "Constant output value", 49, 3E-11, 0.0,0.0,0.0,0,560)
DeclareAlias2("kc.y", "Connector of Real output signal", "kc.k", 1, 7, 49, 0)
DeclareParameter("ka.k", "Constant output value", 50, 9E-11, 0.0,0.0,0.0,0,560)
DeclareAlias2("ka.y", "Connector of Real output signal", "ka.k", 1, 7, 50, 0)
DeclareParameter("theta_0_c.k", "Constant output value", 51, 0.9903, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("theta_0_c.y", "Connector of Real output signal", "theta_0_c.k", 1,\
 7, 51, 0)
DeclareParameter("theta_0_a.k", "Constant output value", 52, 0.0621, 0.0,0.0,0.0,\
0,560)
DeclareAlias2("theta_0_a.y", "Connector of Real output signal", "theta_0_a.k", 1,\
 7, 52, 0)
DeclareParameter("theta_100_c.k", "Constant output value", 53, 0.4384, 0.0,0.0,\
0.0,0,560)
DeclareAlias2("theta_100_c.y", "Connector of Real output signal", \
"theta_100_c.k", 1, 7, 53, 0)
DeclareParameter("theta_100_a.k", "Constant output value", 54, 0.9373, 0.0,0.0,\
0.0,0,560)
DeclareAlias2("theta_100_a.y", "Connector of Real output signal", \
"theta_100_a.k", 1, 7, 54, 0)
DeclareOutput("Rcc_out", "", 0, 0.0, 0.0,0.0,0.0,0,513)
DeclareOutput("phi_ohmic", "", 1, 0.0, 0.0,0.0,0.0,0,513)
DeclareOutput("eta_a", "", 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("eta_c", "", 3, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("phi_ohmic_express.y", "Value of Real output", 0.0, 0.0,0.0,0.0,\
0,513)
DeclareAlias2("Rcc_express.y", "Value of Real output", "Rcc.k", 1, 7, 35, 0)
DeclareAlias2("eta_a_express.y", "Value of Real output", "eta_a", 1, 3, 2, 0)
DeclareAlias2("eta_c_express.y", "Value of Real output", "eta_c", 1, 3, 3, 0)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
EndDataBlock
